image:
  repository: ghcr.io/aureum-cloud/cloudflare-ddns
  tag: latest
  pullPolicy: IfNotPresent

externalConfigMap: ""
externalSecret: ""

config:
  configJson: ""

secrets:
  cloudflareApiToken: ""
