{{- if .Values.secrets.cloudflareApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns-secret
type: Opaque
data:
  CLOUDFLARE_API_TOKEN: {{ .Values.secrets.cloudflareApiToken | b64enc }}
{{- end }}
