apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret | default "cloudflare-ddns-secret" }}
                  key: CLOUDFLARE_API_TOKEN
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.externalConfigMap | default "cloudflare-ddns-config" }}
